name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install gtk
        run: sudo apt-get update && sudo apt-get install libgtk-4-dev  libglib2.0-dev -y

      - name: Lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: latest
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install xvfb and gtk
        run: sudo apt-get update && sudo apt-get install libgtk-4-dev  libglib2.0-dev xvfb -y

      - name: Run test
        run: xvfb-run -a go test -v -timeout 60m -coverprofile cover.out ./... | tee test.out
        shell: bash

      - name: Process results
        if: always()
        uses: malaupa/go-test-coverage-summary-action@v3.0.0
        with:
          with_archive: true

  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install gtk
        run: sudo apt-get update && sudo apt-get install libgtk-4-dev  libglib2.0-dev -y

      - name: Test Build
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --timeout 60m --snapshot

      - name: Store package
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: |
            dist/*.deb
            dist/checksums.txt
          retention-days: 10
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
